import { Fonts, MaxContentWidth, Spacing } from '@/constants/theme';
import { Dimensions, Platform, StyleSheet } from 'react-native';

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');
const WHEEL_SIZE = Math.min(360, SCREEN_WIDTH * 0.95);

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    flexDirection: 'row',
    backgroundColor: '#010302',
  },
  safeArea: {
    flex: 1,
    maxWidth: MaxContentWidth,
    paddingBottom: Platform.OS === 'ios' ? 0 : Spacing.two,
    backgroundColor: '#010302',
  },
  header: {
    paddingHorizontal: Spacing.four,
    paddingTop: Spacing.two,
    paddingBottom: Spacing.two,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderColor: '#161a29',
  },
  logoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  logoIcon: {
    fontSize: 20,
    color: '#ddefb7',
  },
  logoText: {
    letterSpacing: 1.5,
    color: '#9A9FB0',
  },
  scoreBadge: {
    backgroundColor: 'rgba(241, 250, 140, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(241, 250, 140, 0.25)',
    borderRadius: 20,
    paddingHorizontal: Spacing.three,
    paddingVertical: Spacing.one,
  },
  scoreText: {
    color: '#F1FA8C',
    fontSize: 12,
  },
  screenWrapper: {
    flex: 1,
    paddingHorizontal: Spacing.three,
    paddingVertical: Spacing.three,
    justifyContent: 'space-between',
  },
  titleArea: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: Spacing.one,
    paddingHorizontal: 0,
  },
  mainTitle: {
    fontSize: 18,
    lineHeight: 32,
    fontFamily: 'BookkMyungjo_Bold',
    letterSpacing: -0.4
  },
  neonEmeraldGlow: {
    color: '#ddefb7',
    textShadowColor: 'rgba(221, 239, 183, 0.3)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  subtitleText: {
    fontSize: 12,
    color: '#9A9FB0',
    marginTop: 2,
  },
  bookButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0c130a',
    borderWidth: 1,
    borderColor: '#4b5633',
    borderRadius: Spacing.two,
    paddingHorizontal: 12,
    paddingVertical: Spacing.two,
    flexShrink: 0,
  },
  bookButtonText: {
    fontSize: 11,
    color: '#f6faaf',
  },
  skyGardenContainer: {
    flex: 1,
    height: SCREEN_HEIGHT * 0.45,
    minHeight: 320,
    maxHeight: 460,
    backgroundColor: '#0a0d0a',
    borderWidth: 1,
    borderColor: '#272518',
    borderRadius: 24,
    marginTop: 8,
    marginBottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    position: 'relative',
  },
  sanctuarySkyGardenContainer: {
    flex: 1,
    width: '100%',
    maxWidth: 540,
    alignSelf: 'center',
    minHeight: 440,
    maxHeight: Math.min(SCREEN_HEIGHT * 0.72, 640),
    backgroundColor: '#070D14',
    borderWidth: 1,
    borderColor: '#272518',
    borderRadius: 24,
    marginTop: 8,
    marginBottom: 8,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    position: 'relative',
  },
  skyGardenGradientOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: 120,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
  },
  fireflyWrapper: {
    position: 'absolute',
    width: 48,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 30,
  },
  fireflyTouch: {
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  fireflyOuterGlow: {
    position: 'absolute',
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(241, 250, 140, 0.03)',
    transform: [{ scale: 1.5 }],
  },
  fireflyMediumGlow: {
    position: 'absolute',
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'rgba(241, 250, 140, 0.08)',
  },
  fireflyInnerGlow: {
    position: 'absolute',
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: 'rgba(241, 250, 140, 0.2)',
  },
  fireflyCore: {
    position: 'absolute',
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: '#fef9c3',
    shadowColor: '#F1FA8C',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.9,
    shadowRadius: 5,
  },
  sparkleDeco: {
    position: 'absolute',
    top: -4,
    right: -2,
    fontSize: 10,
    color: 'rgba(254, 240, 138, 0.5)',
  },
  plantWrapper: {
    alignItems: 'center',
    zIndex: 20,
  },
  plantContainer: {
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: 'rgba(168, 227, 154, 0.01)',
    borderWidth: 1,
    borderColor: 'rgba(168, 227, 154, 0.04)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: Spacing.two,
  },
  plantVisual: {
    alignItems: 'center',
  },
  potNumberTag: {
    backgroundColor: 'rgba(88, 53, 13, 0.15)',
    borderWidth: 1,
    borderColor: 'rgba(88, 53, 13, 0.3)',
    borderRadius: 20,
    paddingHorizontal: Spacing.two,
    paddingVertical: 4,
    marginTop: Spacing.one,
  },
  potTagText: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#FFB86C',
  },
  potProgressBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  potProgressEmoji: {
    fontSize: 13,
  },
  potProgressEmojiDim: {
    opacity: 0.35,
  },
  seedState: {
    alignItems: 'center',
  },
  seedIcon: {
    fontSize: 32,
  },
  seedLabel: {
    fontSize: 12,
    color: '#9A9FB0',
    marginTop: Spacing.two,
  },
  plantNameText: {
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '600',
    color: '#ffffea',
    textAlign: 'center',
    marginVertical: 4,
    fontFamily: 'BookkMyungjo_Bold',
    letterSpacing: -0.4,
    paddingHorizontal: 8,
    minWidth: 330,
    flexWrap: 'wrap',
  },
  plantGrowthStageText: {
    fontSize: 12,
    color: '#ddefb7',
    marginTop: 4,
  },
  doveWrapper: {
    position: 'absolute',
    bottom: Spacing.two,
    right: Spacing.two,
    zIndex: 35,
  },
  doveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0c130a',
    borderWidth: 1,
    borderColor: '#272518',
    borderRadius: 20,
    paddingHorizontal: Spacing.three,
    paddingVertical: 5,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 6,
  },
  doveText: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#f6faaf',
  },
  potsGridScrollView: {
    width: '100%',
    height: SCREEN_HEIGHT * 0.16 - 12,
    minHeight: 98,
    maxHeight: 128,
    marginTop: 12,
    marginBottom: Spacing.three,
  },
  potsGridScrollContainer: {
    flexDirection: 'row',
    gap: Spacing.two,
    paddingHorizontal: 2,
    paddingVertical: 2,
  },
  potCard: {
    width: 96,
    padding: Spacing.two,
    borderRadius: 16,
    backgroundColor: '#101012',
    borderWidth: 1,
    borderColor: '#272518',
    alignItems: 'center',
    justifyContent: 'center',
  },
  potCardLocked: {
    opacity: 0.4,
  },
  potCardActive: {
    backgroundColor: '#10160c',
    borderColor: '#758651',
  },
  potCardEmoji: {
    fontSize: 20,
    marginBottom: 4,
  },
  potCardName: {
    fontSize: 10,
    color: '#b8b28e',
    textAlign: 'center',
  },
  potCardLevel: {
    fontSize: 11,
    color: '#a6c884',
    marginTop: 2,
  },
  actionBtn: {
    width: '100%',
    paddingVertical: Spacing.three + 2,
    backgroundColor: '#9DBA7D',
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#9DBA7D',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 15,
  },
  actionBtnDisabled: {
    backgroundColor: '#1A1C23',
    shadowOpacity: 0,
  },
  actionBtnContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionBtnText: {
    fontWeight: 'bold',
    color: '#000000',
    fontSize: 14,
    letterSpacing: 0.5,
  },
  actionBtnTextDisabled: {
    color: '#525768',
  },
  titleContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    marginTop: 0,
    marginBottom: 6,
    paddingHorizontal: 0,
  },
  stepIndicator: {
    fontSize: 11,
    color: '#ddefb7',
    fontWeight: 'bold',
    letterSpacing: 1,
    textAlign: 'center',
  },
  stepTitle: {
    fontSize: 14,
    color: '#ffffff',
    marginTop: 4,
    marginBottom: 2,
    textAlign: 'center',
    lineHeight: 20,
  },
  stepSubText: {
    fontSize: 11,
    color: '#9A9FB0',
    marginTop: 2,
    textAlign: 'center',
    lineHeight: 16,
  },
  wheelArea: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 12,
    minHeight: WHEEL_SIZE,
  },
  wheelWrapper: {
    width: WHEEL_SIZE,
    height: WHEEL_SIZE,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  lockIndicatorBadge: {
    position: 'absolute',
    width: 64,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 20,
  },
  lockIndicatorEmoji: {
    fontSize: 11,
    marginBottom: 2,
  },
  lockIndicatorText: {
    fontSize: 8,
    fontWeight: 'bold',
    color: '#FBBF24',
    textAlign: 'center',
  },
  wheelHole: {
    position: 'absolute',
    width: WHEEL_SIZE * 0.48,
    height: WHEEL_SIZE * 0.48,
    backgroundColor: '#090b14',
    borderWidth: 1,
    borderColor: '#272518',
    borderRadius: (WHEEL_SIZE * 0.48) / 2,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.8,
    shadowRadius: 12,
  },
  wheelCenterBtn: {
    width: '82%',
    height: '82%',
    borderRadius: (WHEEL_SIZE * 0.48 * 0.82) / 2,
    backgroundColor: '#9DBA7D',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 8,
    shadowColor: '#9DBA7D',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 10,
  },
  wheelCenterBtnText: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#090b14',
    textAlign: 'center',
    fontFamily: 'Pretendard-Bold',
  },
  holeLabel: {
    fontSize: 11,
    color: '#9A9FB0',
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  holeDotRow: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 8,
  },
  holeDot: {
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: '#272518',
  },
  chosenSection: {
    width: '100%',
  },
  chosenCapsulesGrid: {
    flexDirection: 'row',
    gap: Spacing.two,
    marginBottom: 12,
  },
  capsuleCard: {
    flex: 1,
    height: 104,
    paddingHorizontal: Spacing.two,
    backgroundColor: '#090b14',
    borderWidth: 1,
    borderColor: '#161a29',
    borderRadius: 16,
    alignItems: 'center',
    position: 'relative',
    justifyContent: 'center',
  },
  capsuleCloseBtn: {
    position: 'absolute',
    top: -6,
    right: -6,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#1A1C23',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 30,
    borderWidth: 1,
    borderColor: '#2A2D37',
  },
  closeBtnText: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#9A9FB0',
  },
  capsuleDot: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#161a29',
  },
  capsuleText: {
    fontSize: 11,
    color: '#ffffff',
    marginTop: 6,
    textAlign: 'center',
    lineHeight: 14,
  },
  capsuleSubText: {
    fontSize: 10,
    color: '#9A9FB0',
    marginTop: 2,
    lineHeight: 12,
  },
  capsuleEmpty: {
    alignItems: 'center',
  },
  capsuleEmptyCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    borderStyle: 'dashed',
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyCircleNum: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.3)',
  },
  capsuleEmptyText: {
    fontSize: 10,
    color: 'rgba(255,255,255,0.3)',
    marginTop: 6,
  },
  essenceBeakersRow: {
    flexDirection: 'row',
    gap: Spacing.two,
    backgroundColor: '#0a0c16',
    borderWidth: 1,
    borderColor: '#161a29',
    borderRadius: 16,
    paddingHorizontal: Spacing.two,
    paddingVertical: Spacing.two,
    marginTop: 2,
  },
  beakerCol: {
    flex: 1,
    alignItems: 'center',
  },
  beakerOuter: {
    width: 44,
    height: 52,
    borderWidth: 2,
    borderColor: '#424c66',
    backgroundColor: '#05060a',
    borderRadius: 10,
    overflow: 'hidden',
    justifyContent: 'flex-end',
    position: 'relative',
    marginTop: Spacing.one,
  },
  beakerLip: {
    position: 'absolute',
    top: 0,
    left: '50%',
    marginLeft: -8,
    width: 16,
    height: 3,
    borderBottomWidth: 1.5,
    borderColor: '#424c66',
  },
  beakerLiquidFill: {
    width: '100%',
    opacity: 0.85,
  },
  beakerValText: {
    fontSize: 11,
    color: '#9A9FB0',
    marginTop: Spacing.one,
  },
  canvasContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  canvasBorder: {
    padding: 0,
    backgroundColor: 'transparent',
    borderWidth: 0,
  },
  brushSection: {
    width: '100%',
  },
  brushRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: Spacing.four,
    marginTop: 10,
    marginBottom: 16,
  },
  brushCircle: {
    width: 30,
    height: 30,
    borderRadius: 15,
  },
  brushCircleActive: {
    borderWidth: 2,
    borderColor: '#ffffff',
    transform: [{ scale: 1.1 }],
  },
  coloringActions: {
    flexDirection: 'row',
    gap: Spacing.three,
  },
  resetBtn: {
    width: '25%',
    paddingVertical: Spacing.three,
    backgroundColor: '#1A1C23',
    borderWidth: 1,
    borderColor: '#2A2D37',
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  resetBtnText: {
    color: '#9A9FB0',
    fontSize: 14,
  },
  completeColorBtn: {
    flex: 1,
    paddingVertical: Spacing.three,
    backgroundColor: '#9DBA7D',
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#9DBA7D',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
  },
  completeColorBtnDisabled: {
    backgroundColor: '#1A1C23',
    shadowOpacity: 0,
  },
  completeColorBtnText: {
    color: '#000000',
    fontSize: 14,
  },
  reflectionCard: {
    flex: 1,
    backgroundColor: 'rgba(9, 11, 20, 0.2)',
    borderWidth: 1,
    borderColor: '#161a29',
    borderRadius: 24,
    padding: 0,
    marginVertical: 6,
    justifyContent: 'center',
    position: 'relative',
    shadowColor: '#9DBA7D',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.05,
    shadowRadius: 20,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderColor: '#161a29',
    paddingBottom: Spacing.two,
  },
  cardLogo: {
    fontSize: 11,
    color: '#9DBA7D',
    letterSpacing: 1,
    fontWeight: 'bold',
  },
  cardDate: {
    fontSize: 11,
    color: '#9A9FB0',
  },
  cardBody: {
    alignItems: 'center',
    paddingVertical: Spacing.one + 2,
    paddingHorizontal: 16,
    width: '100%',
  },
  cardStepTitle: {
    fontSize: 15,
    lineHeight: 24,
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 6,
    fontFamily: 'BookkMyungjo_Bold',
  },
  cardStepTitleLv5Shadow: {
    textShadowColor: 'rgba(0, 0, 0, 0.6)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 4,
  },
  cardPlantTag: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0c130a',
    borderWidth: 1,
    borderColor: '#4b5633',
    borderRadius: 20,
    paddingHorizontal: Spacing.three,
    paddingVertical: Spacing.one + 1,
    marginBottom: 10,
    alignSelf: 'center',
  },
  cardPlantTagLv5: {
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    borderColor: 'rgba(168, 227, 154, 0.30)',
    marginTop: 0,
    marginBottom: 28,
  },
  cardPlantTagText: {
    fontSize: 11,
    color: '#ddefb7',
    textAlign: 'center',
    lineHeight: 16
  },
  cardPlantTagTextLv5: {
    textShadowColor: 'rgba(0, 0, 0, 0.6)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 4,
  },
  cardMessageBox: {

    maxWidth: 360,
    alignSelf: 'center',
    backgroundColor: 'transparent',
    borderWidth: 0,
    paddingHorizontal: 0,
    paddingVertical: 4,
    marginVertical: 4,
    marginHorizontal: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardMessage: {
    fontSize: 12,
    lineHeight: 21,
    fontFamily: 'BookkMyungjo_Bold',
    fontWeight: '500',
    color: '#D8D1B3',
    textAlign: 'center',
    paddingHorizontal: 0,
    letterSpacing: -0.4
  },
  cardMessageLv5: {
    color: '#FFEAA7',
    lineHeight: 20,
    textShadowColor: 'rgba(0, 0, 0, 0.6)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 4,
    fontFamily: 'BookkMyungjo_Bold',
    letterSpacing: -0.4
  },
  cardMessageContainerLv5: {
    position: 'absolute',
    bottom: '9%',
    left: '10%',
    right: '10%',
    height: '17%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardStepTitleLv5: {
    fontFamily: Fonts.serif,
    fontSize: 20,
    color: '#FFEAA7',
    fontWeight: 'bold',
    marginBottom: Spacing.two,
    marginTop: Spacing.three,
  },
  lv5SparkleStar: {
    position: 'absolute',
    fontSize: 10,
    color: '#FFEAA7',
    opacity: 0.7,
    textShadowColor: '#FFEAA7',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 4,
  },
  cardFooter: {
    borderTopWidth: 1,
    borderColor: '#161a29',
    paddingTop: Spacing.two,
    alignItems: 'center',
  },
  cardHashtags: {
    fontSize: 11,
    color: '#BD93F9',
    letterSpacing: 0.5,
  },
  exportSection: {
    width: '100%',
    gap: Spacing.two,
  },
  shareBtn: {
    width: '100%',
    paddingVertical: Spacing.three,
    backgroundColor: '#090b14',
    borderWidth: 1,
    borderColor: 'rgba(189, 147, 249, 0.25)',
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  shareBtnText: {
    color: '#BD93F9',
    fontSize: 14,
  },
  cardReturnBtn: {
    width: '100%',
    paddingVertical: Spacing.three + 2,
    backgroundColor: '#9DBA7D',
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#9DBA7D',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
  },
  cardReturnBtnText: {
    color: '#000000',
    fontSize: 14,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  returnBtn: {
    flex: 1,
    paddingVertical: Spacing.three,
    backgroundColor: '#9DBA7D',
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#9DBA7D',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
  },
  returnBtnText: {
    color: '#000000',
    fontSize: 14,
    fontWeight: 'bold',
  },
  archiveScroll: {
    flex: 1,
    marginVertical: Spacing.three,
  },
  archiveScrollContent: {
    gap: Spacing.two,
    paddingBottom: Spacing.four,
  },
  archiveEmpty: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: Spacing.six,
  },
  archiveEmptyIcon: {
    fontSize: 48,
    opacity: 0.5,
  },
  archiveEmptyText: {
    fontSize: 12,
    color: '#ffffff',
    marginTop: Spacing.three,
  },
  archiveEmptySubText: {
    fontSize: 11,
    color: '#9A9FB0',
    marginTop: 4,
    textAlign: 'center',
  },
  archiveItem: {
    backgroundColor: 'rgba(168, 227, 154, 0.02)',
    borderWidth: 1,
    borderColor: '#161a29',
    borderRadius: 16,
    padding: Spacing.three,
  },
  archiveItemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.two,
  },
  archiveItemBadge: {
    backgroundColor: 'rgba(139, 233, 253, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(139, 233, 253, 0.25)',
    borderRadius: 12,
    paddingHorizontal: Spacing.two,
    paddingVertical: 2,
  },
  archiveItemBadgeText: {
    fontSize: 12,
    color: '#8BE9FD',
  },
  archiveItemDate: {
    fontSize: 10,
    color: '#9A9FB0',
  },
  archiveItemDesc: {
    fontSize: 13,
    color: '#9A9FB0',
    lineHeight: 20,
  },
  archiveItemColors: {
    flexDirection: 'row',
    gap: 6,
    marginTop: Spacing.two,
  },
  archiveColorDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
  },
  archiveFooter: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.three,
  },
  resetGameBtn: {
    paddingVertical: 16,
    paddingHorizontal: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  resetGameBtnText: {
    color: 'rgba(255,255,255,0.3)',
    fontSize: 11,
  },
  archiveHeaderContainer: {
    width: '100%',
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
  },
  archiveSettingsBtn: {
    position: 'absolute',
    right: 0,
    top: 0,
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(168, 227, 154, 0.06)',
    borderWidth: 1,
    borderColor: 'rgba(168, 227, 154, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  settingsMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#0c130a',
    borderWidth: 1,
    borderColor: '#272518',
    borderRadius: 16,
    paddingHorizontal: Spacing.three,
    paddingVertical: 14,
  },
  settingsMenuText: {
    fontSize: 14,
    color: '#ffffff',
    fontWeight: '500',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: Spacing.four,
  },
  modalCard: {
    width: '100%',
    maxWidth: 380,
    maxHeight: 500,
    backgroundColor: '#10160c',
    borderWidth: 1.5,
    borderColor: '#758651',
    borderRadius: 28,
    padding: Spacing.four,
    justifyContent: 'space-between',
    shadowColor: '#758651',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 8,
  },
  modalTitleContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'center',
    gap: 8,
    width: '100%',
    borderBottomWidth: 1,
    borderColor: 'rgba(117, 134, 81, 0.3)',
    paddingBottom: Spacing.two,
    marginBottom: 14,
  },
  modalTitleText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#ffffff',
    textAlign: 'left',
    lineHeight: 22,
    includeFontPadding: false,
  },
  modalScroll: {
    marginTop: 0,
    marginBottom: 16,
    maxHeight: 280,
  },
  modalScrollContent: {
    paddingVertical: Spacing.one,
  },
  modalMessageText: {
    fontSize: 13,
    color: 'rgb(184, 178, 142)',
    lineHeight: 18,
    textAlign: 'center',
  },
  modalActions: {
    flexDirection: 'column',
    gap: Spacing.two,
    marginTop: Spacing.one,
  },
  modalOkBtn: {
    width: '100%',
    paddingVertical: Spacing.three,
    backgroundColor: '#9DBA7D',
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalOkBtnFull: {
    width: '100%',
    paddingVertical: Spacing.three,
    backgroundColor: '#9DBA7D',
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalOkText: {
    color: '#000000',
    fontSize: 14,
  },
  modalConfirmBtn: {
    width: '100%',
    paddingVertical: Spacing.three,
    backgroundColor: '#ef4444',
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalConfirmText: {
    color: '#ffffff',
    fontSize: 14,
  },
  modalCancelBtn: {
    width: '100%',
    paddingVertical: Spacing.three,
    backgroundColor: '#1A1C23',
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalCancelText: {
    color: '#9A9FB0',
    fontSize: 14,
  },
  glowingShadow: {
    // iOS-only shadow (Android: use layered Views instead)
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: Platform.OS === 'ios' ? 0.95 : 0,
    shadowRadius: Platform.OS === 'ios' ? 18 : 0,
    elevation: 0,
  },
  glowingShadowActive: {
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: Platform.OS === 'ios' ? 0.98 : 0,
    shadowRadius: Platform.OS === 'ios' ? 22 : 0,
    elevation: 0,
  },
  beakerGlowSvg: {
    position: 'absolute',
    top: -20,
    left: 0,
    right: 0,
    height: 20,
  },
  blossomWrapper: {
    width: 80,
    height: 80,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: 10,
    zIndex: 10,
  },
  blossomGlowAura: {
    width: 44,
    height: 44,
    borderRadius: 22,
    position: 'absolute',
    zIndex: 1,
  },
  blossomSvgWrapper: {
    width: 120,
    height: 120,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 2,
  },
  sparkleStreamContainer: {
    position: 'absolute',
    top: -45,
    left: -25,
    right: -25,
    height: 90,
    zIndex: 5,
  },
  sparkleParticle: {
    position: 'absolute',
    bottom: 0,
    width: 11,
    height: 11,
    borderRadius: 5.5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardStepSubtitle: {
    fontSize: 11,
    color: '#9A9FB0',
    textAlign: 'center',
    marginBottom: 4,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
  cardQuestionBox: {
    backgroundColor: 'rgba(10, 13, 24, 0.6)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.18)',
    borderRadius: 16,
    paddingHorizontal: 8,
    paddingVertical: Spacing.three,
    marginTop: Spacing.four,
    width: '100%',
    maxWidth: 480,
    alignSelf: 'center',
  },
  cardQuestionText: {
    fontSize: 12,
    color: '#FFEAA7',
    lineHeight: 20,
    textAlign: 'center',
    fontWeight: '500',
  },
  diaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 4,
    backgroundColor: 'rgba(189, 147, 249, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(189, 147, 249, 0.35)',
    borderRadius: 20,
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: 8,
    minWidth: 70,
  },
  diaryBtnText: {
    color: '#BD93F9',
    fontSize: 11,
    fontWeight: 'bold',
  },
  textAreaWrapper: {
    backgroundColor: 'rgba(5, 6, 10, 0.6)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 16,
    padding: Spacing.two,
    marginTop: Spacing.two,
  },
  textAreaInput: {
    color: '#ffffff',
    fontSize: 13,
    lineHeight: 20,
    textAlignVertical: 'top',
    minHeight: 60,
    padding: Spacing.one,
  },
  archiveColorDotBtn: {
    width: 24,
    height: 24,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    overflow: 'hidden',
  },
  dotCheckIcon: {
    fontSize: 11,
    lineHeight: 12,
    textAlign: 'center',
  },

  // ---- Toast Notification ----
  toastContainer: {
    position: 'absolute',
    bottom: 120,
    left: 20,
    right: 20,
    backgroundColor: 'rgba(16, 22, 12, 0.96)',
    borderRadius: 20,
    paddingVertical: 15,
    paddingHorizontal: 22,
    borderWidth: 1.5,
    borderColor: '#758651',
    zIndex: 99999,
    elevation: 9999,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#758651',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.45,
    shadowRadius: 16,
  },
  toastText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: 'bold',
    textAlign: 'center',
    lineHeight: 22,
  },

  // ---- Butterfly Modal ----
  butterflyModalHeader: {
    height: 90,
    backgroundColor: 'rgba(189, 147, 249, 0.08)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(189, 147, 249, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  butterflyModalIconRow: {
    width: '100%',
    height: 90,
    position: 'relative',
  },
  butterflyMeetBtn: {
    alignSelf: 'stretch',
    overflow: 'hidden',
    backgroundColor: 'rgba(189, 147, 249, 0.15)',
    borderWidth: 1.5,
    borderColor: 'rgba(189, 147, 249, 0.6)',
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 0 20px rgba(189, 147, 249, 0.3)',
    } : {}),
  },
  butterflyMeetBtnText: {
    color: '#BD93F9',
    fontSize: 15,
    letterSpacing: 0.5,
  },

  // ---- Second Garden Popup ----
  secondGardenGlowBar: {
    height: 4,
    backgroundColor: '#50FA7B',
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 0 16px 4px rgba(80, 250, 123, 0.6)',
    } : {
      shadowColor: '#50FA7B',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.9,
      shadowRadius: 10,
      elevation: 5,
    }),
  },
  secondGardenEmoji: {
    width: 32,
    height: 32,
    marginBottom: 12,
  },
  secondGardenStartBtn: {
    alignSelf: 'stretch',
    overflow: 'hidden',
    backgroundColor: 'rgba(80, 250, 123, 0.15)',
    borderWidth: 1.5,
    borderColor: 'rgba(80, 250, 123, 0.6)',
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 0 20px rgba(80, 250, 123, 0.3)',
    } : {}),
  },
  secondGardenStartBtnText: {
    color: '#50FA7B',
    fontSize: 15,
    letterSpacing: 0.5,
  },

  // ---- Sanctuary View Styles ----
  sanctuaryContainer: {
    flex: 1,
    backgroundColor: '#060D1A',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(80, 250, 123, 0.25)',
    padding: 16,
    overflow: 'hidden',
    position: 'relative',
  },
  sanctuarySunGlow: {
    position: 'absolute',
    top: -50,
    right: -50,
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: 'rgba(255, 234, 167, 0.18)',
    ...(Platform.OS === 'web' ? {
      filter: 'blur(30px)',
    } : {}),
  },
  sanctuaryBanner: {
    backgroundColor: 'rgba(15, 23, 42, 0.85)',
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 20,
    alignItems: 'center',
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 234, 167, 0.3)',
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 4px 20px rgba(0, 0, 0, 0.4)',
    } : {}),
  },
  sanctuaryBannerBadge: {
    backgroundColor: 'rgba(255, 234, 167, 0.15)',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    marginBottom: 8,
  },
  sanctuaryBannerBadgeText: {
    fontSize: 12,
    color: '#FFEAA7',
    fontFamily: 'Pretendard-Bold',
  },
  sanctuaryBannerTitle: {
    fontSize: 18,
    color: '#FFFFFF',
    fontFamily: 'Pretendard-Bold',
    marginBottom: 6,
    textAlign: 'center',
  },
  sanctuaryBannerSub: {
    fontSize: 13,
    color: '#94A3B8',
    fontFamily: 'Pretendard-Medium',
    textAlign: 'center',
    lineHeight: 18,
  },
  sanctuaryBannerOverSky: {
    backgroundColor: 'rgba(15, 23, 42, 0.75)',
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 18,
    alignItems: 'center',
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 234, 167, 0.3)',
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 4px 20px rgba(0, 0, 0, 0.4)',
    } : {}),
  },
  sanctuaryOriginalViewport: {
    flex: 1,
    position: 'relative',
    overflow: 'hidden',
  },
  sanctuaryFlower3DItem: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  floatingCreature: {
    position: 'absolute',
    fontSize: 22,
    opacity: 0.88,
  },
  sanctuaryCompactBanner: {
    position: 'absolute',
    top: 10,
    alignSelf: 'center',
    backgroundColor: 'rgba(10, 15, 30, 0.72)',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: 'rgba(255, 234, 167, 0.4)',
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 2px 12px rgba(0,0,0,0.45)',
    } : {}),
    zIndex: 99,
  },
  sanctuaryCompactBannerText: {
    fontSize: 11,
    color: '#FFEAA7',
    fontFamily: 'Pretendard-Medium',
    letterSpacing: 0.3,
  },
  // Bottom season-complete text only (no box container)
  sanctuaryBottomPanel: {
    position: 'absolute',
    bottom: 5,
    left: 0,
    right: 0,
    alignItems: 'center',
    zIndex: 100,
  },
  sanctuaryBottomNext: {
    fontSize: 13,
    lineHeight: 18,
    color: '#FFEAA7',
    fontFamily: 'Pretendard-Medium',
    letterSpacing: 0.5,
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.8)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
});
